version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
    working_directory: ~/phantomchain/crypto
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.exs" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.exs" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run:
          name: Tests
          command: MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: _build/test/lib/phantomchain_crypto
